version: '3.9'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mini_projeto_fullstack

volumes:
  mongo-data:
    driver: local
